---
- hosts: localhost
  tasks:
  - name: stop hashicorp servers if running
    shell: VBoxManage controlvm "{{ item }}" poweroff
    with_items:
      - "{{ vm }}"
        
  - name: delete hashicorp servers if not running
    shell: VBoxManage unregistervm "{{ item }}" --delete
    with_items:
      - "{{ vm }}"
