---
- hosts: dock
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: copy html code file
    copy:
      src: /home/surendra/ansible/templates/web.j2
      dest: /var/www/html/index.html
      mode: '0777'
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
